default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: end-of-file-fixer

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        files: ^(src/prc/|src/tests/|kedro_cli.py)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.770
  #   hooks:
  #     - id: mypy
  #       files: ^(src/hai/|src/tests/|kedro_cli.py)
  #       args: [] # Read configuration settings from ``mypy.ini`` (override default args).
