log_cols:
  - price
  - minimum_nights
  - lag
  - availability_365
  # - month

fea_drop_columns:
  - adjusted_price
  - maximum_nights
  - name
  - latitude
  - longitude
  - last_review
  - neighbourhood
