log_cols:
  - price
  - minimum_nights
  - lag
  - availability_365
  # - month

fea_drop_columns:
  - adjusted_price
  - maximum_nights
  - name
  - latitude
  - longitude
  - last_review
  - neighbourhood

continous_var:
  - price
  - minimum_night
  - lag
  - number_of_reviews
  - calculated_host_listings_count
